### ISSUE TITLE
Swift Compiler Warning

### ISSUE THREAD

**Issue by jiunnc** [PerfectlySoft/Perfect-MariaDB#6]
I got a Swift Compiler Warning:
Perfect-MariaDB-master/Sources/MariaDB/MySQLStmt.swift:288:17: Initialization of 'UnsafeRawPointer' results in a dangling pointer

The code is as below.

	private func allocated(_ a: [Int8]) -> UnsafeMutableRawBufferPointer? {
		let buffer = UnsafeMutableRawBufferPointer.allocate(byteCount: a.count, alignment: 0)
        let u = UnsafeRawPointer(a)
        if let p = buffer.baseAddress {
			memcpy(p, u, a.count)
		}
		return buffer
	}

My OS X is 10.15.5 and Xcode version is 11.5.

Please help. Thanks

**Comment by RockfordWei** [comment]
fixed on tag 3.0.4. Thank you.

**Comment by jiunnc** [comment]
Thanks a lot.
